(function startAuroraScrollReader(){
  "use strict";
  const data=window.AuroraCore.prepareData(window.AURORA_STATION_DATA); const core=window.AuroraCore; const audio=window.AuroraAudio; const pdf=window.AuroraPdf;
  const root=document.getElementById("story"), progressFill=document.getElementById("progress-fill"), progressBar=document.querySelector(".reader-progress"), progressLabel=document.getElementById("progress-label"), soundToggle=document.getElementById("sound-toggle"), restart=document.getElementById("restart-watch"), live=document.getElementById("screen-reader-status");
  const labels=["Strongly disagree","Disagree a little","Neither agree nor disagree","Agree a little","Strongly agree"];
  const store=(()=>{try{return localStorage}catch{return null}})(); let state=core.loadState(data,store); let revealTimer=null; let interactionLocked=false;
  const el=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
  const paragraphs=(parent,value,className="")=>core.splitParagraphs(value).forEach((text)=>parent.appendChild(el("p",className,text)));
  const persist=()=>core.saveState(data,state,store); const nearBottom=()=>scrollY+innerHeight>=document.documentElement.scrollHeight-280;
  const announce=(text)=>{live.textContent="";setTimeout(()=>{live.textContent=text},20)};
  function updateProgress(){const answered=state.answers.length;progressFill.style.transform=`scaleX(${answered/60})`;progressBar.setAttribute("aria-valuenow",String(answered));progressLabel.textContent=answered===60?"Journey complete":answered?`${answered} of 60`:"The final watch";restart.hidden=!state.onboardingComplete;}
  function scrollToNode(node){if(!node)return;requestAnimationFrame(()=>node.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"center"}));}
  function buildOnboarding(){if(state.onboardingComplete)return;const dialog=el("dialog","station-entry");dialog.innerHTML=`<form class="station-entry-frame"><p class="entry-kicker">AURORA STATION · PRELUDE</p><h1 class="entry-title">Before the watch begins</h1><p class="entry-summary">Enter the name that will appear in the station record.</p><label class="entry-field-label" for="player-name">WATCHKEEPER NAME</label><input id="player-name" class="entry-name-input" maxlength="60" required><section class="calibration-panel" hidden><h2>How to answer the watch</h2><p>Choose how strongly you agree or disagree with each statement about how you generally tend to be.</p><div class="scale-anchors"><span>Strongly disagree</span><span>Strongly agree</span></div><div class="calibration-buttons"></div><p class="response-preview">Choose one response to preview its meaning.</p></section><footer class="entry-footer"><button type="button" class="entry-secondary" hidden>← Edit name</button><button class="entry-primary" type="submit">Continue</button></footer></form>`;document.body.appendChild(dialog);const form=dialog.querySelector("form"),input=dialog.querySelector("input"),calibration=dialog.querySelector(".calibration-panel"),buttons=dialog.querySelector(".calibration-buttons"),preview=dialog.querySelector(".response-preview"),back=dialog.querySelector(".entry-secondary"),primary=dialog.querySelector(".entry-primary");let step=0,chosen=null;
    labels.forEach((label,index)=>{const raw=index+1,button=el("button","entry-signal-choice",String(raw));button.type="button";button.dataset.level=String(raw);button.setAttribute("aria-label",`${raw}. ${label}`);button.onclick=()=>{chosen=raw;buttons.querySelectorAll("button").forEach((item)=>item.classList.toggle("is-selected",item===button));preview.textContent=`${raw} · ${label}`;primary.disabled=false};buttons.appendChild(button)});
    back.onclick=()=>{step=0;calibration.hidden=true;input.hidden=false;dialog.querySelector("label").hidden=false;back.hidden=true;primary.textContent="Continue";primary.disabled=false;input.focus()};
    form.onsubmit=(event)=>{event.preventDefault();if(step===0){const name=core.normalisePlayerName(input.value);if(!name){input.focus();return}dialog.dataset.name=name;step=1;input.hidden=true;dialog.querySelector("label").hidden=true;calibration.hidden=false;back.hidden=false;primary.textContent="Begin the final watch";primary.disabled=!chosen;return}state=core.setPlayerIdentity(data,state,dialog.dataset.name);persist();dialog.close();dialog.remove();render();scrollTo({top:0,behavior:"auto"});announce(`Welcome to the final watch, ${state.playerName}.`)};dialog.showModal();input.focus();}
  function allRevealed(){return data.story.acts.every((act)=>(state.revealed[act.id]||0)>=6)}
  function render(){clearTimeout(revealTimer);const oldY=scrollY;root.replaceChildren();updateProgress();const completedActs=Math.floor(state.answers.length/5);data.story.acts.forEach((act,index)=>{if(index<=completedActs)renderAct(act,index,completedActs)});if(state.answers.length===60&&allRevealed())renderResults();if(!state.onboardingComplete)buildOnboarding();if(oldY>0)requestAnimationFrame(()=>scrollTo({top:oldY,behavior:"auto"}));resumeReveal();}
  function renderAct(act,index,completedActs){const section=el("section","act-scroll");section.dataset.act=act.id;const heading=el("header","act-heading");heading.append(el("p","act-kicker",`ACT ${String(act.number).padStart(2,"0")} / 12 · ${act.time}`),el("h2","act-title",act.title));section.appendChild(heading);const opening=el("div","act-opening");paragraphs(opening,act.opening);section.appendChild(opening);const start=index*5,answered=Math.max(0,Math.min(5,state.answers.length-start));if(index===completedActs&&answered<5)section.appendChild(renderQuestionPanel(act,answered,start));const revealed=state.revealed[act.id]||0;if(answered===5||index<completedActs){const story=el("div","act-continuation");for(let i=0;i<Math.min(revealed,5);i++){const item=act.items[i],raw=state.answers[start+i],segment=el("section","story-segment is-visible");paragraphs(segment,item.context);const branch=core.branchForRaw(data,item,raw);if(branch)paragraphs(segment,branch.transition,"chosen-path");paragraphs(segment,item.convergence);story.appendChild(segment)}if(revealed>=6){const closing=el("section","act-closing is-visible");paragraphs(closing,act.closing);story.appendChild(closing)}section.appendChild(story);if(index===completedActs&&revealed<6)section.appendChild(renderRevealControls(act,revealed))}root.appendChild(section)}
  function renderQuestionPanel(act,local,start){const panel=el("section","reflection-panel");panel.id=`question-${start+local+1}`;panel.tabIndex=-1;panel.append(el("p","reflection-kicker",`WATCHKEEPER REFLECTION · ${String(local+1).padStart(2,"0")} / 05`),el("p","statement-number",`STATEMENT ${String(start+local+1).padStart(2,"0")} / 60`),el("h3","reflection-statement",act.items[local].statement));const anchors=el("div","scale-anchors");anchors.append(el("span","","Strongly disagree"),el("span","","Strongly agree"));panel.appendChild(anchors);const choices=el("div","response-choices");labels.forEach((label,index)=>{const raw=index+1,button=el("button","response-choice",String(raw));button.type="button";button.dataset.level=String(raw);button.setAttribute("aria-label",`${raw}. ${label}`);button.onclick=()=>commitAnswer(start+local,raw,button);choices.appendChild(button)});panel.appendChild(choices);const footer=el("div","reflection-footer");if(local>0){const back=el("button","back-button","← Previous");back.onclick=()=>{state=core.undoWithinAct(data,state);persist();render();requestAnimationFrame(()=>scrollToNode(document.querySelector(".reflection-panel")))};footer.appendChild(back)}footer.appendChild(el("p","response-hint","Choose once to continue automatically. You can go back before the Act story begins."));panel.appendChild(footer);return panel}
  function commitAnswer(index,raw,button){if(interactionLocked)return;interactionLocked=true;button.classList.add("is-selected");state=core.answerAt(data,state,index,raw);persist();setTimeout(()=>{interactionLocked=false;render();const panel=document.querySelector(".reflection-panel");if(panel)scrollToNode(panel)},matchMedia("(prefers-reduced-motion: reduce)").matches?0:320)}
  function renderRevealControls(act,revealed){const controls=el("div","reveal-controls");const status=el("span","reveal-status",revealed?`Passage ${Math.min(revealed+1,6)} of 6`:"The story continues");const speed=el("div","speed-control");["slow","normal","fast"].forEach((value)=>{const button=el("button",(store?.getItem(core.SPEED_KEY)||"normal")===value?"is-selected":"",value[0].toUpperCase()+value.slice(1));button.type="button";button.onclick=()=>{store?.setItem(core.SPEED_KEY,value);speed.querySelectorAll("button").forEach((item)=>item.classList.toggle("is-selected",item===button))};speed.appendChild(button)});const show=el("button","show-now","Show now");show.onclick=()=>{clearTimeout(revealTimer);state=core.setRevealed(data,state,act.id,6);persist();render()};controls.append(status,speed,show);return controls}
  function revealDelay(){return {slow:2400,normal:1450,fast:700}[store?.getItem(core.SPEED_KEY)||"normal"]}
  function resumeReveal(){const act=data.story.acts.find((candidate,index)=>state.answers.length>=(index+1)*5&&(state.revealed[candidate.id]||0)<6);if(!act)return;clearTimeout(revealTimer);revealTimer=setTimeout(()=>{const shouldFollow=nearBottom();state=core.setRevealed(data,state,act.id,(state.revealed[act.id]||0)+1);persist();render();if(shouldFollow){const latest=document.querySelector(`[data-act="${act.id}"] .is-visible:last-child`);scrollToNode(latest)}else showNewPassage()},matchMedia("(prefers-reduced-motion: reduce)").matches?0:revealDelay())}
  function showNewPassage(){let button=document.querySelector(".new-passage-button");if(!button){button=el("button","new-passage-button","New passage below ↓");button.onclick=()=>{button.hidden=true;scrollTo({top:document.documentElement.scrollHeight,behavior:"smooth"})};document.body.appendChild(button)}button.hidden=false}
  function renderResults(){const result=core.analyseProfile(data,state),section=el("section","results");section.id="results";section.append(el("p","act-kicker","DAWN DEBRIEF · FINAL WATCH COMPLETE"),el("h2","act-title",`${result.playerName}, your five-current reflection`),el("p","results-intro",result.overview));const grid=el("div","result-grid");result.elements.forEach((item)=>{const card=el("article","result-card");card.style.setProperty("--result-colour",item.colour);card.append(el("h3","",`${item.element} · ${item.trait}`),el("strong","result-score",`${Number(item.score).toFixed(1)} / 5`),el("p","",item.description));grid.appendChild(card)});section.appendChild(grid);const actions=el("div","result-actions");if(pdf){const story=el("button","report-button","Download story PDF");story.onclick=()=>pdf.downloadStory(data,state,core,"Aurora_Station_Story.pdf");const profile=el("button","report-button","Download profile PDF");profile.onclick=()=>pdf.downloadProfile(data,state,core,"Aurora_Station_Profile.pdf");actions.append(story,profile)}const again=el("button","restart-button","Start again");again.onclick=restartJourney;actions.appendChild(again);section.appendChild(actions);root.appendChild(section)}
  function restartJourney(){if(!confirm("Start Aurora Station again? Saved responses and story progress will be cleared."))return;core.clearState(store);state=core.emptyState();scrollTo({top:0,behavior:"auto"});render()}
  restart.onclick=restartJourney;if(soundToggle&&audio)soundToggle.onclick=()=>audio.toggle?.();render();
})();
