import assert from "node:assert/strict";
import fs from "node:fs";
const core=fs.readFileSync("core-v7.js","utf8");
const app=fs.readFileSync("app-v7.js","utf8");
const css=fs.readFileSync("styles-v7.css","utf8");
const index=fs.readFileSync("index.html","utf8");
assert.match(core,/positions = \[1, 2, 3, 4, 5\]/);
assert.match(core,/6 - raw/);
assert.match(core,/low: \[1, 2\], mid: \[3\], high: \[4, 5\]/);
assert.match(app,/act-opening/);
assert.match(app,/reflection-panel/);
assert.match(app,/story-segment/);
assert.match(app,/New passage below/);
assert.doesNotMatch(app,/DecompressionStream|eval\(/);
assert.match(css,/entry-signal-track::before[\s\S]*display:none/);
assert.match(css,/grid-template-columns:repeat\(5,1fr\)/);
assert.match(index,/core-v7\.js/);
assert.match(index,/app-v7\.js/);
assert.doesNotMatch(index,/v5-payload|ux-scroll-v6/);
console.log("Aurora v7 cumulative story tests passed.");
